import fs from "node:fs/promises";
import { root, readJudicialData, validateJudicialData, buildIndex } from "./lib/judicialData.mjs";

const entries = await readJudicialData();
const errors = validateJudicialData(entries);
if (errors.length) throw new Error(errors.join("\n"));
const index = buildIndex(entries);
const generated = new URL("src/data/judicial/generated/", root);
await fs.mkdir(generated, { recursive: true });
const outputs = {
  "index.json": `${JSON.stringify(index)}\n`,
  "loaders.js": `// Generated by npm run data:build. Edit judicial/people/*.json.\nexport default {\n${Object.keys(index).map((id) => `  "${id}": () => import("../people/${id}.json"),`).join("\n")}\n};\n`,
};
for (const [file, content] of Object.entries(outputs)) {
  const path = new URL(file, generated);
  if (process.argv.includes("--check")) {
    const existing = await fs.readFile(path, "utf8").catch(() => "");
    if (existing.replace(/\r\n/g, "\n") !== content) throw new Error(`Stale generated file: ${file}. Run npm run data:build.`);
  } else {
    await fs.writeFile(path, content);
  }
}
console.log(`${Object.keys(entries).length} people validated; ${Object.keys(index).length} detailed files indexed.`);
